language: node_js
node_js:
 - "12"
cache: yarn
before_script:
 - cd $TRAVIS_BUILD_DIR/frontend
 - yarn install
 - cd $TRAVIS_BUILD_DIR/backend
 - yarn install
script:
 - cd $TRAVIS_BUILD_DIR/frontend
 - yarn run build
 - cd $TRAVIS_BUILD_DIR/backend
 - yarn run build
after_success:
 - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
 - chmod +x send.sh
 - ./send.sh success $WEBHOOK_URL
after_failure:
 - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
 - chmod +x send.sh
 - ./send.sh failure $WEBHOOK_URL
